USE [TutorialDB]
;

SELECT * FROM [dbo].[Countries]

--ALTER TABLE [dbo].[Countries] ALTER COLUMN [Second_City] NVARCHAR(50) NULL

INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(2,'Albania','Tirana',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(3,'Algeria','Algiers',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(4,'Andorra','Andorra la Vella',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(5,'Angola','Luanda',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(6,'Antigua and Barbuda','Saint John''s',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(7,'Argentina','Buenos Aires',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(8,'Armenia','Yerevan',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(9,'Australia','Canberra',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(10,'Austria','Vienna',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(11,'Azerbaijan','Baku',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(12,'Bahamas','Nassau',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(13,'Bahrain','Manama',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(14,'Bangladesh','Dhaka',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(15,'Barbados','Bridgetown',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(16,'Belarus','Minsk',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(17,'Belgium','Brussels',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(18,'Belize','Belmopan',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(19,'Benin','Porto-Novo',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(20,'Bhutan','Thimphu',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(21,'Bolivia','La Paz (administrative), Sucre (judicial)',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(22,'Bosnia and Herzegovina','Sarajevo',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(23,'Botswana','Gaborone',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(24,'Brazil','Brasilia',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(25,'Brunei','Bandar Seri Begawan',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(26,'Bulgaria','Sofia',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(27,'Burkina Faso','Ouagadougou',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(28,'Burundi','Bujumbura',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(29,'Cabo Verde','Praia',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(30,'Cambodia','Phnom Penh',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(31,'Cameroon','Yaounde',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(32,'Canada','Ottawa',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(33,'Central African Republic','Bangui',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(34,'Chad','N''Djamena',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(35,'Chile','Santiago',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(36,'China','Beijing',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(37,'Colombia','Bogotá',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(38,'Comoros','Moroni',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(39,'Democratic Republic of the Congo','Kinshasa',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(40,'Republic of the Congo','Brazzaville',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(41,'Costa Rica','San Jose',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(42,'Cote d''Ivoire','Yamoussoukro',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(43,'Croatia','Zagreb',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(44,'Cuba','Havana',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(45,'Cyprus','Nicosia',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(46,'Czech Republic','Prague',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(47,'Denmark','Copenhagen',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(48,'Djibouti','Djibouti (city)',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(49,'Dominica','Roseau',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(50,'Dominican Republic','Santo Domingo',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(51,'Ecuador','Quito',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(52,'Egypt','Cairo',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(53,'El Salvador','San Salvador',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(54,'Equatorial Guinea','Malabo',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(55,'Eritrea','Asmara',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(56,'Estonia','Tallinn',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(57,'Ethiopia','Addis Ababa',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(58,'Fiji','Suva',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(59,'Finland','Helsinki',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(60,'France','Paris',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(61,'Gabon','Libreville',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(62,'Gambia','Banjul',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(63,'Georgia','Tbilisi',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(64,'Germany','Berlin',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(65,'Ghana','Accra',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(66,'Greece','Athens',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(67,'Grenada','Saint George''s',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(68,'Guatemala','Guatemala City',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(69,'Guinea','Conakry',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(70,'Guinea-Bissau','Bissau',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(71,'Guyana','Georgetown',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(72,'Haiti','Port-au-Prince',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(73,'Honduras','Tegucigalpa',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(74,'Hungary','Budapest',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(75,'Iceland','Reykjavik',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(76,'India','New Delhi',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(77,'Indonesia','Jakarta',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(78,'Iran','Tehran',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(79,'Iraq','Baghdad',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(80,'Ireland','Dublin',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(81,'Israel','Jerusalem',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(82,'Italy','Rome',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(83,'Jamaica','Kingston',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(84,'Japan','Tokyo',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(85,'Jordan','Amman',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(86,'Kazakhstan','Astana',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(87,'Kenya','Nairobi',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(88,'Kiribati','South Tarawa',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(89,'Kosovo','Pristina',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(90,'Kuwait','Kuwait City',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(91,'Kyrgyzstan','Bishkek',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(92,'Laos','Vientiane',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(93,'Latvia','Riga',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(94,'Lebanon','Beirut',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(95,'Lesotho','Maseru',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(96,'Liberia','Monrovia',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(97,'Libya','Tripoli',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(98,'Liechtenstein','Vaduz',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(99,'Lithuania','Vilnius',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(100,'Luxembourg','Luxembourg',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(101,'Macedonia','Skopje',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(102,'Madagascar','Antananarivo',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(103,'Malawi','Lilongwe',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(104,'Malaysia','Kuala Lumpur',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(105,'Maldives','Male',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(106,'Mali','Bamako',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(107,'Malta','Valletta',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(108,'Marshall Islands','Majuro',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(109,'Mauritania','Nouakchott',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(110,'Mauritius','Port Louis',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(111,'Mexico','Mexico City',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(112,'Micronesia','Palikir',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(113,'Moldova','Chisinau',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(114,'Monaco','Monaco',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(115,'Mongolia','Ulaanbaatar',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(116,'Montenegro','Podgorica',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(117,'Morocco','Rabat',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(118,'Mozambique','Maputo',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(119,'Myanmar (Burma)','Naypyidaw',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(120,'Namibia','Windhoek',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(121,'Nauru','Yaren District',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(122,'Nepal','Kathmandu',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(123,'Netherlands','Amsterdam',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(124,'New Zealand','Wellington',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(125,'Nicaragua','Managua',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(126,'Niger','Niamey',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(127,'Nigeria','Abuja',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(128,'North Korea','Pyongyang',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(129,'Norway','Oslo',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(130,'Oman','Muscat',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(131,'Pakistan','Islamabad',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(132,'Palau','Ngerulmud',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(133,'Palestine','Ramallah',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(134,'Panama','Panama City',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(135,'Papua New Guinea','Port Moresby',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(136,'Paraguay','Asunción',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(137,'Peru','Lima',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(138,'Philippines','Manila',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(139,'Poland','Warsaw',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(140,'Portugal','Lisbon',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(141,'Qatar','Doha',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(142,'Romania','Bucharest',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(143,'Russia','Moscow',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(144,'Rwanda','Kigali',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(145,'Saint Kitts and Nevis','Basseterre',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(146,'Saint Lucia','Castries',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(147,'Saint Vincent and the Grenadines','Kingstown',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(148,'Samoa','Apia',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(149,'San Marino','San Marino',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(150,'Sao Tome and Principe','São Tomé',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(151,'Saudi Arabia','Riyadh',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(152,'Senegal','Dakar',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(153,'Serbia','Belgrade',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(154,'Seychelles','Victoria',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(155,'Sierra Leone','Freetown',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(156,'Singapore','Singapore',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(157,'Slovakia','Bratislava',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(158,'Slovenia','Ljubljana',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(159,'Solomon Islands','Honiara',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(160,'Somalia','Mogadishu',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(161,'South Africa','Pretoria (administrative), Cape Town (legislative), Bloemfontein (judicial)',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(162,'South Korea','Seoul',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(163,'South Sudan','Juba',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(164,'Spain','Madrid',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(165,'Sri Lanka','Sri Jayawardenepura Kotte',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(166,'Sudan','Khartoum',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(167,'Suriname','Paramaribo',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(168,'Swaziland','Mbabane',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(169,'Sweden','Stockholm',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(170,'Switzerland','Bern',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(171,'Syria','Damascus',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(172,'Taiwan','Taipei',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(173,'Tajikistan','Dushanbe',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(174,'Tanzania','Dodoma',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(175,'Thailand','Bangkok',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(176,'Timor-Leste','Dili',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(177,'Togo','Lomé',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(178,'Tonga','Nukuʻalofa',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(179,'Trinidad and Tobago','Port of Spain',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(180,'Tunisia','Tunis',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(181,'Turkey','Ankara',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(182,'Turkmenistan','Ashgabat',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(183,'Tuvalu','Funafuti',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(184,'Uganda','Kampala',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(185,'Ukraine','Kyiv',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(186,'United Arab Emirates','Abu Dhabi',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(187,'United Kingdom','London',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(188,'United States of America','Washington, D.C.',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(189,'Uruguay','Montevideo',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(190,'Uzbekistan','Tashkent',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(191,'Vanuatu','Port Vila',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(192,'Vatican City (Holy See)','Vatican City',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(193,'Venezuela','Caracas',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(194,'Vietnam','Hanoi',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(195,'Yemen','Sana''a',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(196,'Zambia','Lusaka',NULL);
INSERT INTO [dbo].[Countries](Country_Id,Country,Capital_City,Second_City)values(197,'Zimbabwe','Harare',NULL);
